steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - dniverification
  - --allow-unauthenticated
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --entry-point=dniverification
  - --region=europe-west3
  - --max-instances=1
  - --timeout=90
  - --memory=128