steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - dniverification
  - --source=.
  - --trigger-http
  - --runtime=python37
  - --entry-point=dniverification
  - --allow-unauthenticated
  - --region=europe-west1